#!/bin/bash
#
# $Id$
#
PROG=$( basename $0 ) 
LOCALIP=$( netstat -rn | awk '/^0\./ { print $2 }' ) 
LOCALIP=${LOCALIP:-"192.168.1.1"}
DBGPRINT=${DBGPRINT:-":"}
DBGPRINT=${DBGPRINT:-"logger -t ${PROG} -p user.debug"}
LOGINF=${LOGINF:-"logger -t ${PROG} -p user.info"}
LOGERR=${LOGERR:-"logger -t ${PROG} -p user.error"}
#

function pingip {
	local loss=$( ping -i 0.5 -w 3 -qc 3 "$1" 2>&1 | sed -ne 's/.*, \([0-9][0-9]*\)% packet loss.*/\1/p' )
	${DBGPRINT} "Ping to $1 has $loss % loss" >&2
	[[ "$loss" = 100 ]] && return 1
	return 0
}

if [ -z "$1" ] 
then
	echo "Usage: $PROG addresses..." >&2
	exit 1
fi

for I in $* 
do 
	if pingip ${I}
	then
		${DBGPRINT} "Can ping ${I}" >&2
		exit 0
	fi
done

if pingip ${LOCALIP}
then
	${DBGPRINT} "Can't ping $* and ping ${LOCALIP} indicates local link ok" >&2
	RC=1
else
	${LOGERR} "Can't ping ${TESTIP} nor ${LOCALIP}. This is unexpected" >&2
	RC=0
fi
exit $RC

# :tabSize=4:indentSize=4:noTabs=true
# vim:ts=4:sw=4
