#!/bin/bash
#
# $Id$
#
PROG=$( basename $0 ) 
SERVER="http://127.0.0.1:8080"
CURLARGS='-s -i -H "Accept: application/json"'
DBGPRINT=${DBGPRINT:-":"}
DBGPRINT=${DBGPRINT:-"logger -t ${PROG} -p user.debug"}
LOGINF=${LOGINF:-"logger -t ${PROG} -p user.info"}
LOGERR=${LOGERR:-"logger -t ${PROG} -p user.error"}
#
if [ $# -ne 2 ]
then
	echo "Usage: $PROG name value"
	exit 1
fi

NAME="$1"
VALUE="$2"

if [ -z "${NAME##[0-9]*}" ]
then
    IDX="${NAME}"
else
	IDX=$( curl ${CURLARGS} "${SERVER}/json.htm?type=devices&filter=light" |awk -F'"' '/"Name" :/ { printf $4 "=" }; /"idx" :/ { printf $4 "\n" }' | awk -F= "/^${NAME}=/ { print \$2 }" )

	if [ -z "${IDX}" ]
	then
		echo "$PROG: Cannot find device for ${NAME}"
		exit 2
	fi
fi

RETURN=$( curl ${CURLARGS} "${SERVER}/json.htm?type=command&param=switchlight&idx=${IDX}&switchcmd=${VALUE}" | awk -F'"' '/status|title/ { printf $4 " " }' )
if [[ $? -eq 0 ]] && [[ $RETURN =~ "OK" ]]
then
	echo "$RETURN"
	exit 0
else
	echo "ERROR: $RETURN"
	exit 3
fi

# :tabSize=4:indentSize=4:noTabs=true
# vim:ts=4:sw=4
